#Runs tasks located in roles/install-docker
- hosts: all
  become: yes
  roles:
    - role: install-docker

- hosts: Deployment
  become: yes
  tasks:
    #Copies bash file over to deployment instance to automate express install, repo clone, and app launch
    - name: Copy bash file to Deployment instance
      ansible.builtin.copy:
        src: install-app.sh
        dest: /home/ec2-user
        remote_src: no
