#Runs tasks located in roles/install-docker
- hosts: all
  become: yes
  roles:
    - role: install-docker

- hosts: Deployment
  become: yes
  tasks:
    #Installs packages to support express app
    - name: Install nodejs and npm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash 
      shell: . ~/.nvm/nvm.sh
      shell: nvm install 16 #latest version not supported by AWS

    #Copies bash file over to deployment instance to automate express install, repo clone, and app launch
    - name: Copy bash file to Deployment instance
      ansible.builtin.copy:
        src: install-app.sh
        dest: /home/ec2-user
        remote_src: no
